function varargout = calDTS(varargin)
% CALDTS MATLAB code for calDTS.fig
%
%   --- calDTS GUI  ---
%
% DESCRIPTION:
%   calDTS is a GUI for calibrating DTS MAT-files generated by 
%   processDTS (GUI), Process_Sensornet and Process_Silixa MATLAB codes.
%
% 	calDTS requires the corresponding calDTS.fig file.
%
% INPUT:
% 	Output file (.mat) from processDTS, Process_Sensornet, or
% 	Process_Silixa.
% 
% 	Required MAT-file Variables:
%         Datetime
%         Distance
%         AntiStokes
%         Stokes
%         Reference Temperatures*
% 
% 	*Reference temperatures from RTDs connected to the DTS system are
% 	automatically detected and parsed when using processDTS,
% 	Process_Sensornet, or Process_Silixa and are usually Tref_1 and
% 	Tref_2.
% 
% 	Additional reference temperatures can be manually added to the
% 	MAT-file using the interp1 command. The matrix dimensions of the
% 	added reference temperature matrix must agree with the dimensions of
% 	the datetime variable. Once the reference temperature
% 	is added the entire workspace must be re-saved.
%
%   For example if the RTD data is copied by columns into two variables
%   rtd_date [1xN] and rtd_temp [1xN] the temperature
% 	could be added by the following command:
%       tref_rtd = interp1(rtd_date', rtd_temp', datetime)
%   NOTE: tref_rtd must be in the form [1xN] for calibration
%         rtd_date and rtd_temp can be cleared/deleted prior to re-saving.
%   
% 	Three point explicit calibration requires 3 reference temperatures.
% 	Three point explicit calibration with a step loss requires 2
% 	reference temperatures.
%
% OUTPUT:
%  	User named MAT-File
%   
%  	Variables:
%       calTemp - calibrated DTS temperatures
%       distance - fiber distance array (from input file)
%       datetime - fiber trace timestamp (from input file)
%       RMSE1, RMSE2, RMSE3 - Root Mean Squared Error (RMSE) for each
%       calibration reference section
%       RMSEavg - average RMSE for all reference points (each reference
%               point is weighted equally).
%       cal_parameters - structure containing calibration parameters
%           and user input.
%           Da, g, and C are calibration parameters
%           z and zVAL are the reference index location used in the calibration
%
% WRITTEN BY: Scott Kobs
% LAST REVISED BY: Scott Kobs, 12/8/2014
%
% ACKNOWLEDGEMENTS:
%   The calibration code utilized in this GUI was originally developed and
%   written by Mark Hausner for CTEMPs.  
%
% REFERENCE:
% Hausner, M. B., F. Suárez, K. E. Glander, N. van de Giesen, J. S. Selker,
%   and S. W. Tyler (2011), Calibrating single-ended fiber-optic Raman
%   spectra distributed temperature sensing data., Sensors (Basel).,
%   11(11), 10859–79, doi:10.3390/s111110859.
%
% See also: processDTS, Process_Sensornet, Process_Silixa, interp1

% Edit the above text to modify the response to help calDTS

% Last Modified by GUIDE v2.5 27-Feb-2018 08:11:46

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @calDTS_OpeningFcn, ...
                   'gui_OutputFcn',  @calDTS_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

function calDTS_OpeningFcn(hObject, eventdata, handles, varargin)
global dtsGUIglobal
handles.output = hObject;
guidata(hObject, handles);
if isempty(dtsGUIglobal) == 0
    if dtsGUIglobal{1} == 1;
        global PathName FileName
        PathName = dtsGUIglobal{2};
        FileName = dtsGUIglobal{3};    
        load_uidata(hObject,handles)
    end
end
im = imread('diagram.JPG');
imshow(im,'Parent',handles.diagram1);
movegui('northwest');
set(handles.save_button,'Visible','off')
set(handles.review_button,'Visible','off')

function varargout = calDTS_OutputFcn(hObject, eventdata, handles) 
varargout{1} = handles.output;

function load_data_Callback(hObject, eventdata, handles)
global FileName PathName
h = msgbox('Select a MATLAB file containing DTS data to be calibrated.','Single-Ended Calibration','modal');
uiwait(h);
clear h;
[ui_filename, ui_pathname] = uigetfile('*.mat');
if ui_pathname ~= 0;
    FileName = ui_filename;
    PathName = ui_pathname;
    load_uidata(hObject,handles)
end

function load_uidata(hObject,handles)
global tref_drop bathT FileName PathName uidata
handles=guidata(hObject);
uidata = load([PathName FileName]);
flag = 0;
if isfield(uidata,{'datetime','distance', 'tempC','Stokes','AntiStokes'}) == 1
    flag = 1;
end
if flag == 0
    h = msgbox('Insufficient data for calibration','modal');
    uiwait(h);
    uidata = [];
	set(handles.loaded_file,'String','DTS *.mat File:');
    return
end
if length(FileName) > 30
    set(handles.loaded_file,'String',{['DTS *.mat File:   ' FileName(1:30) '...']});
else
    set(handles.loaded_file,'String',{['DTS *.mat File:   ' FileName]});
end
uidata.R=log(uidata.Stokes./uidata.AntiStokes);
traces = numel(uidata.datetime);
if traces ~= 0
    q = fieldnames(uidata);
end
    j=0;
for i = 1:length(q)
    eval(strcat(['num = numel(uidata.', q{i}, ');']));
    if num == traces
        if length(q{i}) == 8
            if q{i} == 'datetime'
                continue
            end
            if q{i} == 'tref_int'
                continue
            end
        elseif length(q{i}) == 15
            if q{i} == 'datetime_offset'
                continue
            end
        end
        j=j+1;
        BathVars{j} = q{i};
    end
end
if j == 0
  	h = msgbox('No reference temperature data found for calibration','','error','modal');
    uiwait(h);
    bathT = [];
    tref_drop = {' '};
else 
    for i=1:j
        eval(strcat(['bathT(i,:) = uidata.', BathVars{i}, ';']));
    end
    clear i j num;
    tref_drop ={1:size(bathT,1)+1};
    tref_drop{1} = ' ';
    for i=2:(size(bathT,1)+1);
        str = ['tref ' num2str(i-1)];
        tref_drop{i} = str;
    end
end
columnformat = {'numeric', 'numeric', tref_drop};
set(handles.ztable, 'ColumnFormat', columnformat);
guidata(hObject,handles)

function select_calibration_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function select_calibration_Callback(hObject, eventdata, handles)
if get(handles.select_calibration,'Value') == 3
    set(handles.splice_index,'Visible','on')
    set(handles.splice_offset,'Visible','on')
else
    set(handles.splice_index,'Visible','off')
    set(handles.splice_offset,'Visible','off')
end

function splice_index_Callback(hObject, eventdata, handles)

function splice_index_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function splice_offset_Callback(hObject, eventdata, handles)

function splice_offset_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function plot_data_Callback(hObject, eventdata, handles)
global   bathT tref_drop uidata
    if isfield(uidata,{'tempC'}) == 0;
        h = msgbox('Under ''Dataset to Calibrate'' load a prepaired DTS dataset.','','error','modal');
    else
        uncalT = figure(1);
        set(uncalT,'Visible','off');
        set(uncalT,...
        	'Name','Reference Section Identification',...
            'NumberTitle','off',...
            'color','white',...
            'position',[100 100 600 700]);
        movegui(uncalT,[470 -25]);
        subplot(2,1,1);
        plot(uidata.tempC);
        title('Uncalibrated Temperature');
        xlabel('Array Index');
        ylabel('Temperature (\circC)');
        xlim([1 length(uidata.tempC)]); 
        subplot(2,1,2);
        title('Reference Temperatures');
        xlabel('Date');
        ylabel('Temperature (\circC)');
        if isempty(bathT) == 0
            plot(uidata.datetime,bathT);
            legend(tref_drop{2:end},'Location','best');
            datetick('x','keeplimits');
            xlim([uidata.datetime(1) uidata.datetime(end)]);
        else
            annotation(uncalT,'textbox',...
            [0.33 0.200 0.5 0.12],...
            'String',{'No reference temperatures found.'},...
            'FontWeight','bold',...
            'FontSize',12,...
            'FitBoxToText','off',...
            'LineStyle','none');
        end
        set(uncalT,'Visible', 'on');
    end

function calibrate_button_Callback(hObject, eventdata, handles)
global zREF zINDEX zSPLICE uidata bathT
zREF = get(handles.ztable, 'data');
zINDEX = cell2mat(zREF(:,1:2));
temp_str = char(zREF(:,3));
flag = 0;
if isempty(uidata) == 1
    msgbox('Under ''Dataset to Calibrate'' load a prepaired DTS dataset.','','error','modal');
    return
elseif get(handles.select_calibration,'Value') == 1
    msgbox('Under ''Select Calibration Routine'' use the drop-down menu to specify the calibration routine to be used.','','error','modal');
    return
elseif isempty(bathT) == 1
	msgbox('No reference temperature data found. Unable to proceed with calibration','','error','modal');
	return
elseif all(all(zINDEX(1:3,:),2)) == 0
    msgbox('Under ''Designate Reference Locations'' identify all reference locations. Zero is not a valid index.','','error','modal');
elseif all(zINDEX(:,1)<=zINDEX(:,2)) == 0
    msgbox('Invalid START and END index (START <= END).','modal');
    return
elseif isempty(temp_str) || any(temp_str(1:3,1) ~= 't')
        msgbox('Under ''Designate Reference Locations'' select a valid reference temperature record for all reference locations.','','error','modal');
        return
elseif get(handles.select_calibration,'Value') == 2
    three_point_explicit
    flag = 1;
elseif get(handles.select_calibration,'Value') == 3 
    if isempty(get(handles.splice_index, 'string')) || isempty(get(handles.splice_offset, 'string'))
        msgbox('Identify the step loss index data.','modal');
    else
        zSPLICE(1,1) = str2num(get(handles.splice_index, 'string'));
        zSPLICE(2,1) = str2num(get(handles.splice_offset, 'string'));
        cal_splice
        flag = 1;
    end
end
f = get(0, 'Children');
f = f == 1;
if any(f) == 1
    close 1;
end
if flag == 1
    set(handles.save_button,'Visible','on')
    set(handles.review_button,'Visible','on')
    if get(handles.checkbox_reviewcal,'Value') == 1
        display_cal_results
    end
end
   
function three_point_explicit
global  zINDEX  bathT  zREF calTemp cal_parameters T uidata
ntrace = length(uidata.datetime);
ltrace = length(uidata.distance);
calTemp = zeros(ltrace, ntrace);
g = zeros(1, ntrace);
C = zeros(1, ntrace);
Da = zeros(1, ntrace);
RMSEavg = zeros(1, ntrace);
valRMSE = zeros(1, ntrace);
z = zINDEX(1:3,:);
zVAL = zINDEX(4,:);
str = char(zREF(:,3));
userIDbath = str2num(str(:,end)); %#ok<ST2NM>
bath1 = bathT(userIDbath(1),:);
bath2 = bathT(userIDbath(2),:);
bath3 = bathT(userIDbath(3),:);
T=[bath1;bath2;bath3] + 273.15;
if length(userIDbath) == 4
    Tv = bathT(userIDbath(4),:) + 273.15;
end
for i=1:length(uidata.datetime)
    A(1,1:3)=[1 -T(1,i) T(1,i)*mean(uidata.distance(z(1,1):z(1,2)))];
    A(2,1:3)=[1 -T(2,i) T(2,i)*mean(uidata.distance(z(2,1):z(2,2)))];
    A(3,1:3)=[1 -T(3,i) T(3,i)*mean(uidata.distance(z(3,1):z(3,2)))];
    if det(A)==0
        g(i)=497.6;
        C(i)=1.7243;
        Da(i)=6.38E-5;
        clear A
    else
        Q=A\([T(1,i)*mean(uidata.R(z(1,1):z(1,2),i));T(2,i)*mean(uidata.R(z(2,1):z(2,2),i));T(3,i)*mean(uidata.R(z(3,1):z(3,2),i))]);
        g(i)=Q(1);
        C(i)=Q(2);
        Da(i)=Q(3);
        clear Q A;
    end
    calTemp(:,i)=real(g(i)./(uidata.R(:,i)+C(i)-Da(i)*uidata.distance)) - 273.15;
end
j=0;
for i=z(1,1):z(1,2)
    j=j+1;
    E1(j,:)=(calTemp(i,:)+273.15-T(1,:));
end
j=0;
for i=z(2,1):z(2,2)
    j=j+1;
    E2(j,:)=(calTemp(i,:)+273.15-T(2,:));
end
j=0;
for i=z(3,1):z(3,2)
    j=j+1;
    E3(j,:)=(calTemp(i,:)+273.15-T(3,:));
end 
clear i j checker;
RMSE1 = sqrt(mean(E1.^2,1));
RMSE2 = sqrt(mean(E2.^2,1));
RMSE3 = sqrt(mean(E3.^2,1));
E = [E1; E2; E3];
RMSEavg=sqrt(mean(E.^2));
Bias = mean(E);
    if length(userIDbath) == 4 & any(zVAL==0) == 0
        j=0;
        for i=zVAL(1,1):zVAL(1,2)
            j=j+1;
            V(j,:)=(calTemp(i,:)+273.15-Tv(1,:));
        end
        valRMSE=sqrt(mean(V.^2));
        valBias = mean(V);
    else
        valRMSE = NaN;
        valBias = NaN;
    end
global strT
strT = {['Calibration RMSE:  ' num2str(round(mean(RMSEavg)*1000)/1000)],...
        ['Calibration Bias:      ' num2str(round(mean(Bias)*1000)/1000)],...
        ' ',...
        ['Validation RMSE:   ' num2str(round(mean(valRMSE)*1000)/1000)],...
        ['Validation Bias:       ' num2str(round(mean(valBias)*1000)/1000)]};
msgbox(strT,'modal');
cal_parameters.Da = Da;
cal_parameters.g = g;
cal_parameters.C = C;
cal_parameters.z = z;
cal_parameters.zVAL = zVAL;
cal_parameters.RMSE1 = RMSE1;
cal_parameters.RMSE2 = RMSE2;
cal_parameters.RMSE3 = RMSE3;
cal_parameters.RMSEavg = RMSEavg;
cal_parameters.Bias = Bias;
cal_parameters.valRMSE = valRMSE;
cal_parameters.valBias = valBias;

function cal_splice
global zSPLICE uidata zINDEX z
z = zINDEX(1:3,:);
step_index = zSPLICE(1);
offset_index = zSPLICE(2);
for i=1:length(uidata.datetime)
    checker(1,:) = polyfit(uidata.distance(z(1,1):z(1,2)),uidata.R(z(1,1):z(1,2),i),1);
    checker(2,:) = polyfit(uidata.distance(z(2,1):z(2,2)),uidata.R(z(2,1):z(2,2),i),1);
    checker(3,:) = polyfit(uidata.distance(z(3,1):z(3,2)),uidata.R(z(3,1):z(3,2),i),1);
    offset_step = uidata.R(step_index - offset_index,i)...
                - uidata.R(step_index + offset_index,i)...
                + mean(checker(:,1))*(uidata.distance(step_index + offset_index)-uidata.distance(step_index - offset_index));
    ostep(i) = offset_step;
    uidata.R(step_index:length(uidata.distance),i) = uidata.R(step_index:length(uidata.distance),i) + offset_step;
end
three_point_explicit

function display_cal_results
global zINDEX T calTemp uidata cal_parameters
    Tc = T - 273.15;
    cal_results = figure(2);
        set(cal_results,'Visible','off');
        set(cal_results,...
            'name','Calibration Results',...
            'color','white',...
            'position',[100 100 600 700],...
            'NumberTitle','off');
   	movegui(cal_results,[470 -25]);
    subplot(2,3,1:3) 
    a = plot(Tc(1,:),calTemp(zINDEX(1,1):zINDEX(1,2),:),'rx');
    hold on
 	b = plot(Tc(2,:),calTemp(zINDEX(2,1):zINDEX(2,2),:),'bx');
    c = plot(Tc(3,:),calTemp(zINDEX(3,1):zINDEX(3,2),:),'gx');
    title('Reference and Calibration Temperature Comparison')
    xlabel('Reference Temperature (\circC)')
    ylabel('Calibrated Temperature (\circC)')
    rline = [min(min(Tc))-5 max(max(Tc))+5];
    plot(rline,rline,'--b');  
    hold off
    xlim(rline)
    ylim(rline)
    legend([a(1),b(1),c(1)],'Ref1','Ref2','Ref3','Location','Best');
    subplot(2,3,4)
    plot(uidata.datetime,cal_parameters.g)
    xlim([uidata.datetime(1) uidata.datetime(end)])
    datetick('x','keeplimits')
    ylabel('\gamma')
    subplot(2,3,5)
    plot(uidata.datetime,cal_parameters.C)
    xlim([uidata.datetime(1) uidata.datetime(end)])
    datetick('x','keeplimits')
    ylabel('C')
   	subplot(2,3,6)
    plot(uidata.datetime,cal_parameters.Da)
    xlim([uidata.datetime(1) uidata.datetime(end)])
    datetick('x','keeplimits')
    ylabel('\Delta\alpha')
	set(cal_results,'Visible','on');
        
function save_button_Callback(hObject, eventdata, handles)
global calTemp cal_parameters uidata zSPLICE zREF T 
distance = uidata.distance;
datetime = uidata.datetime;
[FileName,PathName] = uiputfile('*.mat');
if FileName ~= 0
    outfile = ['''' PathName FileName ''''];
    saveline=strcat(['save ',outfile,' distance datetime calTemp cal_parameters']);
    eval(saveline);
    if get(handles.checkbox_gen_report,'Value') == 1
        pName = get(handles.projectname_txt,'String');
        outfile2 = [ PathName FileName(1:end-4) '_Report'];
        calReport(get(handles.select_calibration,'Value'), zSPLICE, zREF, T,  uidata, calTemp, cal_parameters, pName, outfile2);
    end
    close all
end

function checkbox_gen_report_Callback(hObject, eventdata, handles)

function checkbox_reviewcal_Callback(hObject, eventdata, handles)

function projectname_txt_Callback(hObject, eventdata, handles)

function projectname_txt_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function review_button_Callback(hObject, eventdata, handles)
display_cal_results

function figure1_CloseRequestFcn(hObject, eventdata, handles)
clearvars -global FileName PathName bathT calTemp cal_parameters dtsGUIglobal ...
    strT T tref_drop uidata zINDEX zREF zSPLICE
delete(hObject);
