function [ tref, error_flag ] = probe2tref( FILE, datetime, DayOffset, PROB )
% prob2tref Version 1(1/16/2015)
% prob2tref: function to interpolate reference temperatures from RBRsolo
%       temperature probes to match datetime array from DTS systems.
%       Temperatures are linearly interpolated in time to match the time
%       stamp of the corresponding DTS trace. Automatically verifies whether
%       the time range of the two datasets overlaps. In the case the ranges
%       do not fully overlap the indices of the overlapping range for the
%       DTS datetime vector will be printed to the screen.
% 
% USAGE: RBR_tref(RBRmat,datetime,DayOffset)
%       RBRmat = RBR structure generated by Ruskin software
%           Ruskin V1.8.17 File > Export Dataset > Matlab MAT
%       datetime = datetime array of DTS traces in decimal days
%     	DayOffset (optional) = correction factor to adjust for any
%       	discrepancy between the recorded time in the RBRsolo files and
%           the actual time (e.g. daylight savings time, time zone
%          	corrections).  DayOffset should be entered in decimal days. If
%          	the function is called without a DayOffset argument, the
%          	RBRsolo probe time will be used.
% 
% INPUTS: (variables) RBRmat, datetime
% 
% OUTPUT: (variable) tref
%       tref = interpolated reference temperature that correspond to
%              datetime array
% 
% WRITTEN BY: Scott Kobs
% Revised to work with GUI

% Load FILE according to PROB for the correct file format 
if PROB == 1 %RBR Solo Case

	tline = char(strcat('temp = load(''',FILE,''');'));
    eval(tline);

    var = fieldnames(temp);

    tline = char(strcat('RBRmat = temp.',var,';'));
    eval(tline);

    pTEMP = RBRmat.data;
    pDATE = datenum(RBRmat.sampletimes, 'dd/mm/yy HH:MM:SS.FFF PM'); %dd/mm/yy HH:MM:SS.FFF PM

elseif PROB == 2 %HOBO Case

	tline = char(strcat('fid = fopen(''',FILE,''');'));
    eval(tline);
    
    % HeaderLines = 3
    % Data/time = column 2
    % Temp = column 3
    raw = textscan(fid, repmat('%s',1,3), 'delimiter',',','HeaderLines',2, 'CollectOutput',true);
    fclose(fid);
    
    raw=raw{1};
    
	pDATE = datenum(raw(:,2)); 
    pTEMP = str2num(cell2mat(raw(:,3)));
    
elseif PROB == 3 %CSV Case

    tline = char(strcat('fid = fopen(''',FILE,''');'));
    eval(tline);

	% Data/time = column 1
    % Temp = column 2
    raw = textscan(fid, '%s%f', 'delimiter',',', 'CollectOutput',true);
    % check to make sure brought in correctly
    if ~isempty(raw{2})
    %try
        pDATE = datenum(raw{1});
        pTEMP = cell2mat(raw(:,2));
        
    else
        % deal with header line
        %catch
        raw = textscan(fid, '%s%f', 'HeaderLines',1,'delimiter',',', 'CollectOutput',true);
        pDATE = datenum(raw{1});
        pTEMP = cell2mat(raw(:,2));
    end
    
    fclose(fid);
    
elseif PROB == 4 %XLS Case [DATE, TEMP]
    
    tline = char(strcat('[~,~,raw] = xlsread(''',FILE,''');'));
    eval(tline);

	% Data/time = column 1
    % Temp = column 2
    pTEMP = cell2mat(raw(:,2));
    pDATE = datenum(raw(:,1));
    
else
    disp('Invalid Prob')
    FILE
    return
end

if exist('DayOffset')
    pDATE=pDATE+DayOffset;
end

error_flag = 0;
bLIM = [1 length(datetime)];

% datestr(datetime(1))
% datestr(datetime(end))
% 
% datestr(pDATE(1))
% datestr(pDATE(end))


% Verify DTS datetime and pDATE overlap
% Case that datetime and pDATE do not overlap at all
if pDATE(1) > datetime(end) | pDATE(end) < datetime(1)
    fprintf('\n\n')
    fprintf('PROCESSING ERROR:\n')
    disp(FILE)
    fprintf('ERROR: DTS and Probe datetime range do not overlap\n')
    
    fprintf(['DTS range:\t\t' datestr(datetime(1)) ' to ' datestr(datetime(end))])
    fprintf(['\nProbe range:\t' datestr(pDATE(1)) ' to ' datestr(pDATE(end)) '\n\n'])
    
    error_flag = 1;
    tref = NaN;
    return % Stop datetime check and return NaN array and error_flag
end


% Check that pDATE starts before DTS datetime
if pDATE(1) > datetime(1)
    fprintf('\n\n')
    fprintf('PROCESSING ERROR:\n')
    disp(FILE)
    fprintf('ERROR: DTS datetime starts before Probe datetime\n')
    fprintf(['DTS start time:\t\t' datestr(datetime(1)) '\nProbe start time:\t' datestr(pDATE(1)) '\n\n']);

    % Determine where datasets start overlapping
    i = 1;
    while datetime(i) < pDATE(1) & i < length(datetime);
        i = i + 1;
    end
    bLIM(1) = i;
    
	error_flag = 2;
end

% Check that DTS datetime ends before pDATE
if pDATE(end) < datetime(end)
    
    if error_flag == 0
        fprintf('\n\n')
        fprintf('PROCESSING ERROR:\n')
        disp(FILE)
    end
    
    fprintf('ERROR: Probe datetime ends before DTS datetime\n')        
    fprintf(['Last DTS time:\t\t' datestr(datetime(end)) '\nLast probe time:\t' datestr(pDATE(end)) '\n\n']);

   	% Determine where datasets stop overlapping
    i = length(datetime);
    while datetime(i) > pDATE(end);
        i = i - 1;
    end
    bLIM(2) = i;
    
    error_flag = error_flag + 1;
end



if error_flag > 0;
    fprintf(['The datasets overlap from:\n' datestr(datetime(bLIM(1))) ...
        ' to ' datestr(datetime(bLIM(2))) '\n'])
    fprintf('DTS records that overlap corresponds to: %i to %i\n\n',bLIM)
    fprintf('Only process overlapping data sets.\n',bLIM)
end


% Only if date time fully overlaps DTS datetime will tref be calculated
if error_flag == 0
    tref = interp1(pDATE,pTEMP,datetime);
else
    tref = NaN(1,length(datetime));
end


end

