function varargout = tref2DTS(varargin)
% TREF2DTS MATLAB code for tref2DTS.fig
%
%
%   --- tref2DTS GUI BETA ---
%   TESTED WITH MATLAB VERSIONS 2012a AND 2014a RUNNING ON WINDOWS 7
%   MAC OS X IS NOT SUPPORTED.
%
% DESCRIPTION:
%	  tref2DTS is a GUI for adding reference bath temperatures to an existing
%	  MAT-file generated by the processDTS GUI. Reference temperature data must be
%	  in one of the following formats:
%           -RBRsolo MAT-file exported from Ruskin Software
%           -HOBO Temp Logger temp only exported from HOBOware
%           -CSV files formated DATE,Temp (no headers)
%           -XLS files formated [DATE][TEMP] (no headers)
% 
%     tref2DTS requires the corresponding tref2DTS.fig file and the
%     the probe2tref script.
%
% INPUT:
%       processDTS GUI MAT-file
%       Reference temperature data file (*.mat, *.csv, *.xls)
%       File type (list menu)
%               CSV [Date,Temp], Hobo, RBRsolo, XLS [Date,Temp]
%       Date/Time Offset in decimal format for time shifting data
%
% OUTPUT:
%       Appended MAT-file [dtsFILE]
%
%       Appended Variables:
%           tref_# (Array of interpolated values)
%               A unique # is assigned to each temperature record
%           tref2DTS_output {Cell}
%               Cell the contains the added variable and its orignal file
%
% USAGE:
%      Load DTS Dataset created by the processDTS GUI (.mat)using the 'Load
%      Dataset' button.
% 
%      Use the 'Remove' and 'Add' buttons to load reference tempreature
%      data sets to be interpolated.
%
%      Select the file/probe type from the 'Type' drop down menu.
%
%      Input 'Time Offset' value (default value is zero)
%
%      After all files are loaded press 'Complile' in order to process each
%      files and appended the loaded dataset.
%
%      Temperatures are interpolated linearly using the interp1 command
%      built into matlab.
%      
%      Errors for each file are printed to the screen. In the event of a
%      time shift error or overlap error data from the file will not be
%      appended to the DTS MAT-file.
%
%      Each file must be formated to specifically match the specified type.
%      In the event that data is not processed or in formated differently,
%      we recomend copying the date and temperure record into an excel file
%      and processing the data in that way.
%
%      Unsuported data can manually be added using the interp1 command.
%
% WRITTEN BY: Scott Kobs
%
% See also: processDTS, calDTS

% Edit the above text to modify the response to help tref2DTS

% Last Modified by GUIDE v2.5 05-May-2015 10:50:33

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @tref2DTS_OpeningFcn, ...
                   'gui_OutputFcn',  @tref2DTS_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

function tref2DTS_OpeningFcn(hObject, eventdata, handles, varargin)
handles.output = hObject;
guidata(hObject, handles);
global addFlag data tdata dtsGUIglobal
addFlag = 0;
tdata = cell(1,4);
set(handles.uitable2,'Units','Pixels');
tbl_wP = get(handles.uitable2,'Position');
tbl_w = (tbl_wP(3)-1);
tw2  = {floor(.45*tbl_w) floor(.3*tbl_w) floor(.25*tbl_w)};
set(handles.uitable2,'ColumnEditable',[false true true],...
    'ColumnName',{'File Name', 'Type', 'Time Offset'},...
    'RowName','',...
    'Data',{'Add File','Select',0},...
    'Selected','off',...
    'ColumnFormat',{'char',{'CSV [Date,Temp]','Hobo','RBRsolo','XLS [Date,Temp]'},'numeric'},...
    'ColumnWidth',tw2,...
    'CellSelectionCallback',@(src,evnt)set(src,'UserData',evnt.Indices))
if isempty(dtsGUIglobal) == 0
    if dtsGUIglobal{1} == 1;
        global PathName FileName
        PathName = dtsGUIglobal{2};
        FileName = dtsGUIglobal{3};  
        if length(FileName) > 30
            set(handles.text1,'String',{['DTS *.mat file:   ' FileName(1:30) '...']});
        else
            set(handles.text1,'String',{['DTS *.mat file:   ' FileName]});
        end
        data = load([PathName FileName]);
    end
end
movegui('northwest');

function varargout = tref2DTS_OutputFcn(hObject, eventdata, handles) 
varargout{1} = handles.output;

function load_Callback(hObject, eventdata, handles)
global FileName PathName data
[ui_filename, ui_pathname] = uigetfile('*.mat');
if ui_pathname ~= 0;
    FileName = ui_filename;
    PathName = ui_pathname;
	if length(FileName) > 30
        set(handles.text1,'String',{['DTS *.mat file:   ' FileName(1:30) '...']});
    else
        set(handles.text1,'String',{['DTS *.mat file:   ' FileName]});
    end
    data = load([PathName FileName]);
end

function add_Callback(hObject, eventdata, handles)
global addFlag tdata P
if exist(P) == 0
    [ui_f, ui_p] = uigetfile('*.*');
else
    [ui_f, ui_p] = uigetfile([P '*.*']);
end
if ui_p ~= 0
    F = ui_f;
    P = ui_p;
    odat = get(handles.uitable2,'Data');
    rows = size(odat,1);
    if addFlag == 0;
        addFlag = 1;
        tdata = cell(1,4);
        tdata(1,:) = {F 'Select' '0' P};
    else        
        tdata(:,2:3) = odat(:,2:3);
        tdata(rows+1,:) = {F 'Select' '0' P};    
    end
    ndat = tdata(:,1:3);
    set(handles.uitable2,'Data',ndat);
end

function remove_Callback(hObject, eventdata, handles)
global addFlag tdata
rc = get(handles.uitable2,'UserData');
if isempty(rc) == 0;
    row = rc(1);
    s = size(tdata,1);
    if row == 1;
        if row == s
            tdata = cell(1,4);
            tdata = {'Add File' 'Select' '0'};
            addFlag = 0;
        else
            disp('remove 1');
            tdata = tdata(2:end,:);
        end
    elseif row == s
        disp('last row');
        tdata = tdata(1:(row-1),:);
    else
        disp('normal row');
        temp = tdata;
        temp(row:s-1,:) = tdata(row+1:end,:);
        tdata = temp(1:s-1,:);
    end
        ndat = tdata(:,1:3);
    set(handles.uitable2,'data',ndat);
else
    h = msgbox('Please select a file to remove.','modal');
end

function uitable2_CellEditCallback(hObject, eventdata, handles)
global tdata
z = get(handles.uitable2,'data');
tdata(:,2:3) = z(:,2:3);

function compile_Callback(hObject, eventdata, handles)
global tdata data PathName trefT dtsGUIglobal
if isempty(PathName) == 1
	h = msgbox('Load DTS *.mat dataset to append.','','error','modal');
    return
end
for i = 1:size(tdata,1);
    check = char(tdata(i,2));
    if check(1:3) == 'Sel';
        file = tdata(i,1);
        str = ['Please select a file type for ' file];
        h = msgbox(str,'','error','modal');
        return 
    end
end
j = 0;
for i = 1:size(tdata,1);
    fun = char(tdata(i,2));
    fn = fun(1:2);
	pf = strcat(tdata(i,4), tdata(i,1));
    switch fn
        case 'RB'
            [tref,error] = probe2tref(pf,data.datetime,str2num(tdata{i,3}),1);     
        case 'Ho'
            [tref,error] = probe2tref(pf,data.datetime,str2num(tdata{i,3}),2);                     
        case 'CS'
            [tref,error] = probe2tref(pf,data.datetime,str2num(tdata{i,3}),3);                      
        otherwise
            [tref,error] = probe2tref(pf,data.datetime,str2num(tdata{i,3}),4);
    end
    if error == 0;
        j = j+1;
        trefT(j,:) = tref;
    end
end
if j ~= 0;
    save_data;
    close all
    choice = questdlg('Would you like to calibrate the data set?', ...
        '','Yes','No','Yes');
    switch choice
        case 'Yes'
                dtsGUIglobal{1} = 1;
                calDTS
                clearvars -global addFlag tdata data trefT P
        case 'No'
                clearvars -global addFlag tdata data FileName PathName trefT P
    end
else
    msgbox('No data was appended to the data set.','','error','modal');
end
    
function save_data
global data trefT FileName PathName tdata
q = fieldnames(data);
traces = length(data.datetime);
j = 0;
for i = 1:length(q);
    eval(strcat(['num = numel(data.', q{i}, ');']));
    if num == traces
        if length(q{i}) == 8;
            if q{i} == 'datetime';
                continue
            end
            if q{i} == 'tref_int';
                continue
            end
        end
        j = j+1;
    end
end
if isfield(data,'tref2DTS_output') == 0
    for i = 1:size(trefT,1);
        j = j +1;
        if i == 1
            tref2DTS_output = {'TREF VAR','FILE','TIME OFFSET'};
        end
        tline = strcat(['tref_',num2str(j),'=trefT(i,:);']);
        eval(tline);
        tref_save{i} = (['tref_' num2str(j)]);
        tref2DTS_output{i+1,1} = (['tref_' num2str(j)]);
        tref2DTS_output{i+1,2} = tdata{i,1};
        tref2DTS_output{i+1,3} = tdata{i,3};
    end
else
    tref2DTS_output = data.tref2DTS_output;
    output_i = size(data.tref2DTS_output,1);
    for i = 1:size(trefT,1)
        j = j +1;
        tline = strcat(['tref_',num2str(j),'=trefT(i,:);']);
        eval(tline);
        tref_save{i} = (['tref_' num2str(j)]);
        tref2DTS_output{output_i+i,1} = (['tref_' num2str(j)]);
        tref2DTS_output{output_i+i,2} = tdata{i,1};
        tref2DTS_output{output_i+i,3} = tdata{i,3};
    end  
end

 tline = char(strcat('save(''',PathName, FileName, ''',tref_save{:}, ''tref2DTS_output'', ''-append'');'));
 eval(tline);
 
function figure1_CloseRequestFcn(hObject, eventdata, handles)
clearvars -global addFlag tdata data trefT P FileName PathName
delete(hObject);
